# Generated by Django 5.2.1 on 2025-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_orderitem_price_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
